# Generated by Django 4.1.6 on 2023-02-12 08:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersReceipts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_name', models.CharField(max_length=128)),
                ('cooking_time', models.CharField(max_length=32)),
                ('image', models.ImageField(blank=True, null=True, upload_to='users_receipt_images')),
                ('link', models.CharField(blank=True, max_length=128, null=True)),
                ('steps', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
