# Generated by Django 4.1.6 on 2023-02-20 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'категорию',
                'verbose_name_plural': 'Категории еды',
            },
        ),
        migrations.CreateModel(
            name='ReceiptCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'категорию',
                'verbose_name_plural': 'Категории рецептов',
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_name', models.CharField(max_length=128)),
                ('cooking_time', models.CharField(max_length=32)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='receipt_images')),
                ('first_ingridient', models.CharField(max_length=64)),
                ('second_ingridient', models.CharField(max_length=64)),
                ('third_ingridient', models.CharField(blank=True, max_length=64, null=True)),
                ('fourth_ingridient', models.CharField(blank=True, max_length=64, null=True)),
                ('fifth_ingridient', models.CharField(blank=True, max_length=64, null=True)),
                ('sixth_ingridient', models.CharField(blank=True, max_length=64, null=True)),
                ('seventh_ingridient', models.CharField(blank=True, max_length=64, null=True)),
                ('eighth_ingridient', models.CharField(blank=True, max_length=64, null=True)),
                ('nineth_ingridient', models.CharField(blank=True, max_length=64, null=True)),
                ('tenth_ingridient', models.CharField(blank=True, max_length=64, null=True)),
                ('first_step', models.TextField()),
                ('second_step', models.TextField()),
                ('third_step', models.TextField(blank=True, null=True)),
                ('fourth_step', models.TextField(blank=True, null=True)),
                ('fifth_step', models.TextField(blank=True, null=True)),
                ('sixth_step', models.TextField(blank=True, null=True)),
                ('seventh_step', models.TextField(blank=True, null=True)),
                ('eighth_step', models.TextField(blank=True, null=True)),
                ('nineth_step', models.TextField(blank=True, null=True)),
                ('tenth_step', models.TextField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.receiptcategory')),
            ],
            options={
                'verbose_name': 'рецепт',
                'verbose_name_plural': 'Рецепт',
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('permission', models.BooleanField()),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.foodcategory')),
            ],
            options={
                'verbose_name': 'еду',
                'verbose_name_plural': 'Еда',
            },
        ),
    ]
