# Generated by Django 4.1.6 on 2023-02-08 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_receiptcategory_alter_foodcategory_options_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.receiptcategory'),
        ),
    ]
